apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: hellowhale-knative
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/vamsijakkula/hellowhale-knative
